baseURL: "https://VarunArora14.github.io/"
languageCode: en-us
title: V'log
theme: PaperMod
enableRobotsTXT: True

pagination:
  pagerSize: 1000 # show all posts on home page

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema., can be changed to development
  title: V'log
  description: "Hello there, my name is Varun Arora and here is my blog post that captures my learning so far"
  keyWords:
    [
      blog,
      Portfolio,
      PaperMod,
      Kubernetes,
      GenAI,
      Python,
      Microservices,
      Distributed Systems,
      DevOps,
      Linux,
    ]
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  social: true

  # home-info mode
  homeInfoParams:
    Title: ðŸ‘‹ Hello there. Welcome to V'log
    Content: Hi, Iâ€™m Varun. Currently I am building scalable data pipelines and centralized data warehouses, distributed systems and following production DevOps practices. In this blog Iâ€™ll share my learnings and insights as I explore and learn new technologies. Glad to have you here! ðŸ˜Š

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/varun-arora-335225192/"
    - name: leetcode
      url: "https://leetcode.com/u/RDXV/"
    - name: github
      url: "https://github.com/VarunArora14"

  assets:
    disableHLJS: true
    favicon: "favicons/favicon.ico"
    #     favicon16x16: "<link / abs url>"
    # favicon32x32: "favicons/favicon-32x32.png"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: Search
      name: Search
      url: /search/
      weight: 15
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Archive
      name: Archive
      url: /archive/
      weight: 25
    - identifier: Portfolio
      name: Portfolio
      url: /portfolio/
      weight: 30
    - identifier: resume
      name: My Resume
      url: https://drive.google.com/file/d/1vm_fc6zV8aULVz4tfjJocgw0T9w9Es3X/view?usp=drive_link
      weight: 35
taxonomies:
  category: categories
  tag: tags

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    noClasses: false # use CSS classes so theme can provide dark/light variants
    style: paraiso-light
    styleDark: paraiso-dark
  goldmark:
    renderer:
      unsafe: true
